package com.company.enums;

public enum Positions {
    PROJECT_MANAGER,
    SERVICES_DEVELOPER,
    SYSTEM_ADMINISTRATOR,
    CHIEF_TECHNOLOGY_OFFICER,
    IT_DIRECTOR,
    JAVA_DEVELOPER,
    JUNIOR_SOFTWARE_ENGINEER;
}
